<?php
$res = @include '../../main.inc.php'; // For root directory
if (! $res)
	$res = @include '../../../main.inc.php'; // For "custom" directory
if (! $res)
	die("Include of main fails");

dol_include_once('/volvo/class/reprise.class.php');
dol_include_once('/volvo/class/expertise.class.php');
dol_include_once('/volvo/lib/reprise.lib.php');
require_once DOL_DOCUMENT_ROOT . '/core/class/html.form.class.php';
require_once DOL_DOCUMENT_ROOT . '/core/class/doleditor.class.php';
require_once DOL_DOCUMENT_ROOT . '/contact/class/contact.class.php';
require_once DOL_DOCUMENT_ROOT . '/user/class/user.class.php';

$action = GETPOST('action', 'alpha');
$id = GETPOST('id', 'int');
$confirm = GETPOST('confirm', 'alpha');
$exp = GETPOST('exp', 'int');
$form = new Form($db);
$expertise = new Expertise($db);

$reprise = new Reprise($db);
$reprise->fetch($id);
$reprise->fetch_thirdparty();
$reprise->updatestatus($reprise->id);
$num = $reprise->fetchAll('','',0,0,array('t.fk_lead'=>$id));
$lines = $reprise->lines;

$form = new Form($db);

$actif = 'info' . $id;

if ($action =='create'){
	$actif2 = 'exp_create';
}else{
	$actif2 = 'exp'.$exp;
	$expertise->fetch($exp);
}

if ($action == 'create_expertise' && $user->rights->volvo->modif_exp){
	foreach($expertise->value_array as $value){
		if (isset($_POST[$value])){
			$expertise->$value = GETPOST($value);
		}
	}
	if(isset($_POST['date_exp_'])){$expertise->date_exp = dol_mktime(0, 0, 0, GETPOST('date_exp_month'), GETPOST('date_exp_day'), GETPOST('date_exp_year'));}
	if(isset($_POST['date_essai_'])){$expertise->date_essai = dol_mktime(0, 0, 0, GETPOST('date_essai_month'), GETPOST('date_essai_day'), GETPOST('date_essai_year'));}
	$res = $expertise->create($user);
		if ($res){
			//$actif2 = 'exp' . $res;
		header('Location:' . $_SERVER["PHP_SELF"] . '?id=' . $id.'&action=&exp=' . $res);
	} else {
		header('Location:' . $_SERVER["PHP_SELF"] . '?id=' . $id.'&action=create&exp=' . $res);
	}
}

if ($action == 'update_expertise' && $user->rights->volvo->modif_exp){
	foreach($expertise->value_array as $value){
		if (isset($_POST[$value])){
			$expertise->$value = GETPOST($value);
		}
	}
	if(isset($_POST['date_exp_'])){$expertise->date_exp = dol_mktime(0, 0, 0, GETPOST('date_exp_month'), GETPOST('date_exp_day'), GETPOST('date_exp_year'));}
	if(isset($_POST['date_essai_'])){$expertise->date_essai = dol_mktime(0, 0, 0, GETPOST('date_essai_month'), GETPOST('date_essai_day'), GETPOST('date_essai_year'));}
	$res = $expertise->update();
	if ($res==1){
		header('Location:' . $_SERVER["PHP_SELF"] . '?id=' . $id.'&action=&exp=' . $exp);
	} else {
		header('Location:' . $_SERVER["PHP_SELF"] . '?id=' . $id.'&action=update&exp=' . $exp);
	}
}

if ($action == 'confirm_delete' && $confirm == 'yes' && $user->admin) {
	$res = $expertise->delete();
	header('Location:' . dol_buildpath("/volvo/reprise/card.php", 1) . '?id=' . $oid.'&action=&exp=');
}

llxHeader('', 'reprise');


$expertise->fetchAll('','',0,0,array('t.fk_reprise'=>$id));
$head = info_prepare_head2($expertise->liste_exp,$id);
dol_fiche_head($head, $actif2, 'reprise', 0, dol_buildpath('/volvo/img/object_iron02.png', 1), 1);
$rang = count($expertise->liste_exp)+1;
if ($action == 'create' && $user->rights->volvo->modif_exp){
	print '<form name="createexpertise" action="' . $_SERVER["PHP_SELF"] . '?id=' . $id . '&exp=' . $exp .'" method="POST">';
	print '<input type="hidden" name="token" value="' . $_SESSION['newtoken'] . '">';
	print '<input type="hidden" name="action" value="create_expertise">';
	print '<input type="hidden" name="fk_reprise" value="' . $id . '">';
	print '<input type="hidden" name="fk_rang" value="' . $rang . '">';
	print '<TABLE width="100%">';
		print '<TR>';
			print '<TD valign="top" width="100%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR><TD width="30%" rowspan="2"><img src="' . dol_buildpath('/volvo/img/logo theobald.png',2) . '" height="60" width="142"></TD><TD><H1>ETAT GENERAL DE LA REPRISE</H1></TD></TR>';
				print '</TABLE>';
				print '</br>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD>';
				print '<TABLE width="100%"  class="border">';
					print '<TR class="liste_titre">';
						print '<TD rowspan="4" width="2%" align="center">O</BR>r</BR>g</BR>a</BR>n</BR>e</BR>s</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Moteur</b></TD>';
						print '<TD><input type="text" name="moteur" size="35" value=""/></TD>';
						print '<TD><b>Transmission</b></TD>';
						print '<TD><input type="text" name="transmission" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Embrayage</b></TD>';
						print '<TD><input type="text" name="embrayage" size="35" value=""/></TD>';
						print '<TD><b>Pont</b></TD>';
						print '<TD><input type="text" name="pont" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Boite de Vitesse</b></TD>';
						print '<TD><input type="text" name="bv" size="35" value=""/></TD>';
						print '<TD><b>Freins</b></TD>';
						print '<TD><input type="text" name="freins" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="8" width="2%" align="center">E</BR>x</BR>t</BR>é</BR>r</BR>i</BR>e</BR>u</BR>r</BR> </BR>c</BR>a</BR>b</BR>i</BR>n</BR>e</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Déflecteurs G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_defG',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_defD',$expertise->liste[1],'',1) . '</TD>';
						print '<TD><b>Pare choc AV G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_parechoc_av_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_parechoc_av_D',$expertise->liste[1],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Déflecteur de Toit</b></TD>';
						print '<TD>' . $form->selectarray('fk_defT',$expertise->liste[1],'',1) . '</TD>';
						print '<TD><b>Calandre</b></TD>';
						print '<TD>' . $form->selectarray('fk_calandre',$expertise->liste[2],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Visière</b></TD>';
						print '<TD>' . $form->selectarray('fk_visiere',$expertise->liste[2],'',1) . '</TD>';
						print '<TD><b>Clignotants AV G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_clignotant_av_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_clignotant_av_D',$expertise->liste[1],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Rétroviseur accostage</b></TD>';
						print '<TD>' . $form->selectarray('fk_retroA',$expertise->liste[2],'',1) . '</TD>';
						print '<TD><b>Longe de porte G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_longe_porte_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_longe_porte_D',$expertise->liste[1],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Rétroviseurs G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_retroG',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_retroD',$expertise->liste[1],'',1) . '</TD>';
						print '<TD><b>Portillons de coffre AV G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_porte_coffre_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_porte_coffre_D',$expertise->liste[1],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Blocs Optiques AV G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_bloc_opt_av_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_bloc_opt_av_D',$expertise->liste[1],'',1) . '</TD>';
						print '<TD><b>Portières G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_porte_cabine_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_porte_cabine_D',$expertise->liste[1],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Enjoliveurs de Phares G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_enjo_phare_av_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_enjo_phare_av_D',$expertise->liste[1],'',1) . '</TD>';
						print '<TD><input type="text" name="div_ext_cabine" size="20" value=""/></TD>';
						print '<TD><input type="text" name="comm_div_ext_cabine" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="9" width="2%" align="center">C</BR>h</BR>â</BR>s</BR>s</BR>i</BR>s</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Roue de secours</b></TD>';
						print '<TD>' . $form->selectarray('fk_roue_secours',$expertise->liste[3],'',1) . '</TD>';
						print '<TD><b>Ailes AR G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_aile_ar_G',$expertise->liste[2],'',1) . ' / ' . $form->selectarray('fk_aile_ar_D',$expertise->liste[2],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Flexibles électriques / Air</b></TD>';
						print '<TD>' . $form->selectarray('fk_flexibles',$expertise->liste[4],'',1) . '</TD>';
						print '<TD><b>Feux AR G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_feux_ar_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_feux_ar_D',$expertise->liste[1],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Grille alu sur châssis</b></TD>';
						print '<TD>' . $form->selectarray('fk_grille_alu',$expertise->liste[5],'',1) . '</TD>';
						print '<TD><b>Supports de feux AR G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_support_feux_ar_G',$expertise->liste[1],'',1) . ' / ' . $form->selectarray('fk_support_feux_ar_D',$expertise->liste[1],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Batteries</b></TD>';
						print '<TD>' . $form->selectarray('fk_batteries',$expertise->liste[6],'',1) . '</TD>';
						print '<TD><b>Pneu AV % usure</b></TD>';
						print '<TD>' . $form->selectarray('usure_pneu_av',$expertise->liste[15],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Jupes latérales G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_jupe_G',$expertise->liste[2],'',1) . ' / ' . $form->selectarray('fk_jupe_D',$expertise->liste[2],'',1) . '</TD>';
						print '<TD><b>Pneu AR1 % usure</b></TD>';
						print '<TD>' . $form->selectarray('usure_pneu_ar1',$expertise->liste[15],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoirs Gasoil G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_reservoir_GO_G',$expertise->liste[7],'',1) . ' / ' . $form->selectarray('fk_reservoir_GO_D',$expertise->liste[7],'',1) . '</TD>';
						print '<TD><b>Pneu AR2 % usure</b></TD>';
						print '<TD>' . $form->selectarray('usure_pneu_ar2',$expertise->liste[3],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoir AdBlue</b></TD>';
						print '<TD>' . $form->selectarray('fk_reservoir_adblue',$expertise->liste[6],'',1) . '</TD>';
						print '<TD><b>Pneu AR3 % usure</b></TD>';
						print '<TD>' . $form->selectarray('usure_pneu_ar3',$expertise->liste[3],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoir Hydraulique</b></TD>';
						print '<TD>' . $form->selectarray('fk_reservoir_hydro',$expertise->liste[8],'',1) . '</TD>';
						print '<TD><input type="text" name="div_chassis" size="20" value=""/></TD>';
						print '<TD><input type="text" name="comm_div_chassis" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="6" width="2%" align="center">I</BR>n</BR>t</BR>.</BR> </BR>c</BR>a</BR>b</BR>i</BR>n</BR>e</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Kit Outillage + Cric</b></TD>';
						print '<TD>' . $form->selectarray('fk_kit_outils_cric',$expertise->liste[9],'',1) . '</TD>';
						print '<TD><b>Autoradio / Téléphone</b></TD>';
						print '<TD>' . $form->selectarray('fk_autoradio',$expertise->liste[13],'',1) . ' / ' . $form->selectarray('fk_telephone',$expertise->liste[13],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Chappe de remorquage</b></TD>';
						print '<TD>' . $form->selectarray('fk_chappe',$expertise->liste[10],'',1) . '</TD>';
						print '<TD><b>Tapis de Sol / Nombre</b></TD>';
						print '<TD>' . $form->selectarray('fk_tapis_sol',$expertise->liste[13],'',1) . ' / <input type="text" name="nb_tapis_sol" size="10" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat Interieur</b></TD>';
						print '<TD>' . $form->selectarray('fk_etat_interieur',$expertise->liste[11],'',1) . '</TD>';
						print '<TD><b>Pare Brise</b></TD>';
						print '<TD>' . $form->selectarray('fk_parebrise',$expertise->liste[14],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat tableau de bord</b></TD>';
						print '<TD>' . $form->selectarray('fk_etat_TDB',$expertise->liste[12],'',1) . '</TD>';
						print '<TD><b>Clé de contact et réservoir</b></TD>';
						print '<TD>' . $form->selectarray('fk_cles',$expertise->liste[10],'',1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat des couchettes</b></TD>';
						print '<TD>' . $form->selectarray('fk_etat_couchette',$expertise->liste[11],'',1) . '</TD>';
						print '<TD><b>Kilomètres</b></TD>';
						print '<TD><input type="text" name="kilometres" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre">';
						print '<TD rowspan="8" width="2%" align="center">P</BR>o</BR>r</BR>t</BR>e</BR>u</BR>r</BR> </BR>/</BR> </BR>S</BR>e</BR>m</BR>i</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Barre anti-encastrement</b></TD>';
						print '<TD><input type="text" name="comm_barres_AE" size="35" value=""/></TD>';
						print '<TD><b>Grue</b></TD>';
						print '<TD><input type="text" name="comm_grue" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Baches</b></TD>';
						print '<TD><input type="text" name="comm_baches" size="35" value=""/></TD>';
						print '<TD><b>Hayon</b></TD>';
						print '<TD><input type="text" name="comm_hayon" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Caisse</b></TD>';
						print '<TD><input type="text" name="comm_caisse" size="35" value=""/></TD>';
						print '<TD><b>Crochet Attelage</b></TD>';
						print '<TD><input type="text" name="comm_crochet_attelage" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Benne</b></TD>';
						print '<TD><input type="text" name="comm_benne" size="35" value=""/></TD>';
						print '<TD><b>Groupe frigo</b></TD>';
						print '<TD><input type="text" name="comm_groupe_frigo" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Portes arrières</b></TD>';
						print '<TD><input type="text" name="comm_portes_ar" size="35" value=""/></TD>';
						print '<TD><b>Intérieur</b></TD>';
						print '<TD><input type="text" name="comm_interieur" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Plancher</b></TD>';
						print '<TD><input type="text" name="comm_plancher" size="35" value=""/></TD>';
						print '<TD><b>Plancher - Fosse</b></TD>';
						print '<TD><input type="text" name="comm_plancher_fosse" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>ridelles</b></TD>';
						print '<TD><input type="text" name="comm_ridelles" size="35" value=""/></TD>';
						print '<TD><input type="text" name="div_porteur_semi" size="20" value=""/></TD>';
						print '<TD><input type="text" name="comm_div_porteur_semi" size="35" value=""/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre">';
						print '<TD colspan="5" align="center">Autres observations</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="5" align="center">';
						$doleditor = new DolEditor('autres_observations', '', '', 80, 'dolibarr_details', 'In', false, false, $conf->global->FCKEDITOR_ENABLE || $conf->global->FCKEDITOR_ENABLE_SOCIETE, 4, 90);
						$doleditor->Create();
						print '</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD colspan="2">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD colspan="2"><b> Expertise faite à </b><input type="text" name="lieu" size="20" value=""/> le ' . $form->select_date('', 'date_exp_',0,0,1,'',1,1,1,0,'','','') . '</TD>';
						print '<TD colspan="2"><b> Essai éffectué par ' . $form->select_dolusers('','fk_testeur',1) . ' le ' . $form->select_date('', 'date_essai_',0,0,1,'',1,1,1,0,'','','') . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="2"><b> L' ."'" . 'utilisateur vendeur' . $form->selectcontacts($reprise->fk_soc,'','fk_client_contact',1) .'</TD>';
						print '<TD colspan="2"><b> Le rédacteur' . $form->select_dolusers('','fk_expert',1) .'</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="2">Signature et Cachet</TD>';
						print '<TD colspan="2">Signature</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="4"></BR></BR></BR></BR><b>NB : Sous réserve de constatations effectuées par nos ateliers lors de la restitution.</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
	print '</TABLE>';

	print '<div class="tabsAction">';
 	print '<input type="submit" class="button" value="' . $langs->trans("Save") . '">';
	print '&nbsp;<input type="button" class="button" value="' . $langs->trans("Cancel") . '" onClick="javascript:history.go(-1)">';
	print '</div>';
	print '</form>';

} elseif ($action =='edit' && $user->rights->volvo->modif_exp){

	print '<form name="updateexpertise" action="' . $_SERVER["PHP_SELF"] . '?id=' . $id . '&exp=' . $exp .'" method="POST">';
	print '<input type="hidden" name="token" value="' . $_SESSION['newtoken'] . '">';
	print '<input type="hidden" name="action" value="update_expertise">';
	print '<input type="hidden" name="exp" value="' . $expertise->rowid . '">';
	print '<input type="hidden" name="fk_reprise" value="' . $expertise->fk_reprise . '">';
	print '<TABLE width="100%">';
		print '<TR>';
			print '<TD valign="top" width="100%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR><TD width="30%" rowspan="2"><img src="' . dol_buildpath('/volvo/img/logo theobald.png',2) . '" height="60" width="142"></TD><TD><H1>ETAT GENERAL DE LA REPRISE</H1></TD></TR>';
				print '</TABLE>';
				print '</br>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD>';
				print '<TABLE width="100%"  class="border">';
					print '<TR class="liste_titre">';
						print '<TD rowspan="4" width="2%" align="center">O</BR>r</BR>g</BR>a</BR>n</BR>e</BR>s</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Moteur</b></TD>';
						print '<TD><input type="text" name="moteur" size="35" value="' . $expertise->moteur . '"/></TD>';
						print '<TD><b>Transmission</b></TD>';
						print '<TD><input type="text" name="transmission" size="35" value="' . $expertise->transmission . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Embrayage</b></TD>';
						print '<TD><input type="text" name="embrayage" size="35" value="' . $expertise->embrayage . '"/></TD>';
						print '<TD><b>Pont</b></TD>';
						print '<TD><input type="text" name="pont" size="35" value="' . $expertise->pont . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Boite de Vitesse</b></TD>';
						print '<TD><input type="text" name="bv" size="35" value="' . $expertise->bv . '"/></TD>';
						print '<TD><b>Freins</b></TD>';
						print '<TD><input type="text" name="freins" size="35" value="' . $expertise->freins . '"/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="8" width="2%" align="center">E</BR>x</BR>t</BR>é</BR>r</BR>i</BR>e</BR>u</BR>r</BR> </BR>c</BR>a</BR>b</BR>i</BR>n</BR>e</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Déflecteurs G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_defG',$expertise->liste[1],$expertise->fk_defG,1) . ' / ' . $form->selectarray('fk_defD',$expertise->liste[1],$expertise->fk_defD,1) . '</TD>';
						print '<TD><b>Pare choc AV G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_parechoc_av_G',$expertise->liste[1],$expertise->fk_parechoc_av_G,1) . ' / ' . $form->selectarray('fk_parechoc_av_D',$expertise->liste[1],$expertise->fk_parechoc_av_D,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Déflecteur de Toit</b></TD>';
						print '<TD>' . $form->selectarray('fk_defT',$expertise->liste[1],$expertise->fk_defT,1) . '</TD>';
						print '<TD><b>Calandre</b></TD>';
						print '<TD>' . $form->selectarray('fk_calandre',$expertise->liste[2],$expertise->fk_calandre,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Visière</b></TD>';
						print '<TD>' . $form->selectarray('fk_visiere',$expertise->liste[2],$expertise->fk_visiere,1) . '</TD>';
						print '<TD><b>Clignotants AV G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_clignotant_av_G',$expertise->liste[1],$expertise->fk_clignotant_av_G,1) . ' / ' . $form->selectarray('fk_clignotant_av_D',$expertise->liste[1],$expertise->fk_clignotant_av_D,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Rétroviseur accostage</b></TD>';
						print '<TD>' . $form->selectarray('fk_retroA',$expertise->liste[2],$expertise->fk_retroA,1) . '</TD>';
						print '<TD><b>Longe de porte G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_longe_porte_G',$expertise->liste[1],$expertise->fk_longe_porte_G,1) . ' / ' . $form->selectarray('fk_longe_porte_D',$expertise->liste[1],$expertise->fk_longe_porte_D,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Rétroviseurs G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_retroG',$expertise->liste[1],$expertise->fk_retroG,1) . ' / ' . $form->selectarray('fk_retroD',$expertise->liste[1],$expertise->fk_retroD,1) . '</TD>';
						print '<TD><b>Portillons de coffre AV G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_porte_coffre_G',$expertise->liste[1],$expertise->fk_porte_coffre_G,1) . ' / ' . $form->selectarray('fk_porte_coffre_D',$expertise->liste[1],$expertise->fk_porte_coffre_D,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Blocs Optiques AV G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_bloc_opt_av_G',$expertise->liste[1],$expertise->fk_bloc_opt_av_G,1) . ' / ' . $form->selectarray('fk_bloc_opt_av_D',$expertise->liste[1],$expertise->fk_bloc_opt_av_D,1) . '</TD>';
						print '<TD><b>Portières G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_porte_cabine_G',$expertise->liste[1],$expertise->fk_porte_cabine_G,1) . ' / ' . $form->selectarray('fk_porte_cabine_D',$expertise->liste[1],$expertise->fk_porte_cabine_D,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Enjoliveurs de Phares G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_enjo_phare_av_G',$expertise->liste[1],$expertise->fk_enjo_phare_av_G,1) . ' / ' . $form->selectarray('fk_enjo_phare_av_D',$expertise->liste[1],$expertise->fk_enjo_phare_av_D,1) . '</TD>';
						print '<TD><input type="text" name="div_ext_cabine" size="20" value="' . $expertise->div_ext_cabine . '"/></TD>';
						print '<TD><input type="text" name="comm_div_ext_cabine" size="35" value="' . $expertise->comm_div_ext_cabine . '"/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="9" width="2%" align="center">C</BR>h</BR>â</BR>s</BR>s</BR>i</BR>s</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Roue de secours</b></TD>';
						print '<TD>' . $form->selectarray('fk_roue_secours',$expertise->liste[3],$expertise->fk_roue_secours,1) . '</TD>';
						print '<TD><b>Ailes AR G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_aile_ar_G',$expertise->liste[2],$expertise->fk_aile_ar_G,1) . ' / ' . $form->selectarray('fk_aile_ar_D',$expertise->liste[2],$expertise->fk_aile_ar_D,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Flexibles électriques / Air</b></TD>';
						print '<TD>' . $form->selectarray('fk_flexibles',$expertise->liste[4],$expertise->fk_flexibles,1) . '</TD>';
						print '<TD><b>Feux AR G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_feux_ar_G',$expertise->liste[1],$expertise->fk_feux_ar_G,1) . ' / ' . $form->selectarray('fk_feux_ar_D',$expertise->liste[1],$expertise->fk_feux_ar_D,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Grille alu sur châssis</b></TD>';
						print '<TD>' . $form->selectarray('fk_grille_alu',$expertise->liste[5],$expertise->fk_grille_alu,1) . '</TD>';
						print '<TD><b>Supports de feux AR G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_support_feux_ar_G',$expertise->liste[1],$expertise->fk_support_feux_ar_G,1) . ' / ' . $form->selectarray('fk_support_feux_ar_D',$expertise->liste[1],$expertise->fk_support_feux_ar_D,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Batteries</b></TD>';
						print '<TD>' . $form->selectarray('fk_batteries',$expertise->liste[6],$expertise->fk_batteries,1) . '</TD>';
						print '<TD><b>Pneu AV % usure</b></TD>';
						print '<TD>' . $form->selectarray('usure_pneu_av',$expertise->liste[15],$expertise->usure_pneu_av,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Jupes latérales G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_jupe_G',$expertise->liste[2],$expertise->fk_jupe_G,1) . ' / ' . $form->selectarray('fk_jupe_D',$expertise->liste[2],$expertise->fk_jupe_D,1) . '</TD>';
						print '<TD><b>Pneu AR1 % usure</b></TD>';
						print '<TD>' . $form->selectarray('usure_pneu_ar1',$expertise->liste[15],$expertise->usure_pneu_ar1,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoirs Gasoil G / D</b></TD>';
						print '<TD>' . $form->selectarray('fk_reservoir_GO_G',$expertise->liste[7],$expertise->fk_reservoir_GO_G,1) . ' / ' . $form->selectarray('fk_reservoir_GO_D',$expertise->liste[7],$expertise->fk_reservoir_GO_D,1) . '</TD>';
						print '<TD><b>Pneu AR2 % usure</b></TD>';
						print '<TD>' . $form->selectarray('usure_pneu_ar2',$expertise->liste[3],$expertise->usure_pneu_ar2,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoir AdBlue</b></TD>';
						print '<TD>' . $form->selectarray('fk_reservoir_adblue',$expertise->liste[6],$expertise->fk_reservoir_adblue,1) . '</TD>';
						print '<TD><b>Pneu AR3 % usure</b></TD>';
						print '<TD>' . $form->selectarray('usure_pneu_ar3',$expertise->liste[3],$expertise->usure_pneu_ar3,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoir Hydraulique</b></TD>';
						print '<TD>' . $form->selectarray('fk_reservoir_hydro',$expertise->liste[8],$expertise->fk_reservoir_hydro,1) . '</TD>';
						print '<TD><input type="text" name="div_chassis" size="20" value="' . $expertise->div_chassis . '"/></TD>';
						print '<TD><input type="text" name="comm_div_chassis" size="35" value="' . $expertise->comm_div_chassis . '"/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="6" width="2%" align="center">I</BR>n</BR>t</BR>.</BR> </BR>c</BR>a</BR>b</BR>i</BR>n</BR>e</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Kit Outillage + Cric</b></TD>';
						print '<TD>' . $form->selectarray('fk_kit_outils_cric',$expertise->liste[9],$expertise->fk_kit_outils_cric,1) . '</TD>';
						print '<TD><b>Autoradio / Téléphone</b></TD>';
						print '<TD>' . $form->selectarray('fk_autoradio',$expertise->liste[13],$expertise->fk_autoradio,1) . ' / ' . $form->selectarray('fk_telephone',$expertise->liste[13],$expertise->fk_telephone,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Chappe de remorquage</b></TD>';
						print '<TD>' . $form->selectarray('fk_chappe',$expertise->liste[10],$expertise->fk_chappe,1) . '</TD>';
						print '<TD><b>Tapis de Sol / Nombre</b></TD>';
						print '<TD>' . $form->selectarray('fk_tapis_sol',$expertise->liste[13],$expertise->fk_tapis_sol,1) . ' / <input type="text" name="nb_tapis_sol" size="10" value="' . $expertise->nb_tapis_sol . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat Interieur</b></TD>';
						print '<TD>' . $form->selectarray('fk_etat_interieur',$expertise->liste[11],$expertise->fk_etat_interieur,1) . '</TD>';
						print '<TD><b>Pare Brise</b></TD>';
						print '<TD>' . $form->selectarray('fk_parebrise',$expertise->liste[14],$expertise->fk_parebrise,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat tableau de bord</b></TD>';
						print '<TD>' . $form->selectarray('fk_etat_TDB',$expertise->liste[12],$expertise->fk_etat_TDB,1) . '</TD>';
						print '<TD><b>Clé de contact et réservoir</b></TD>';
						print '<TD>' . $form->selectarray('fk_cles',$expertise->liste[10],$expertise->fk_cles,1) . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat des couchettes</b></TD>';
						print '<TD>' . $form->selectarray('fk_etat_couchette',$expertise->liste[11],$expertise->fk_etat_couchette,1) . '</TD>';
						print '<TD><b>Kilomètres</b></TD>';
						print '<TD><input type="text" name="kilometres" size="35" value="' . $expertise->kilometres . '"/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre">';
						print '<TD rowspan="8" width="2%" align="center">P</BR>o</BR>r</BR>t</BR>e</BR>u</BR>r</BR> </BR>/</BR> </BR>S</BR>e</BR>m</BR>i</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Barre anti-encastrement</b></TD>';
						print '<TD><input type="text" name="comm_barres_AE" size="35" value="' . $expertise->comm_barres_AE . '"/></TD>';
						print '<TD><b>Grue</b></TD>';
						print '<TD><input type="text" name="comm_grue" size="35" value="' . $expertise->comm_grue . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Baches</b></TD>';
						print '<TD><input type="text" name="comm_baches" size="35" value="' . $expertise->comm_baches . '"/></TD>';
						print '<TD><b>Hayon</b></TD>';
						print '<TD><input type="text" name="comm_hayon" size="35" value="' . $expertise->comm_hayon . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Caisse</b></TD>';
						print '<TD><input type="text" name="comm_caisse" size="35" value="' . $expertise->comm_caisse . '"/></TD>';
						print '<TD><b>Crochet Attelage</b></TD>';
						print '<TD><input type="text" name="comm_crochet_attelage" size="35" value="' . $expertise->comm_crochet_attelage . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Benne</b></TD>';
						print '<TD><input type="text" name="comm_benne" size="35" value="' . $expertise->comm_benne . '"/></TD>';
						print '<TD><b>Groupe frigo</b></TD>';
						print '<TD><input type="text" name="comm_groupe_frigo" size="35" value="' . $expertise->comm_groupe_frigo . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Portes arrières</b></TD>';
						print '<TD><input type="text" name="comm_portes_ar" size="35" value="' . $expertise->comm_portes_ar . '"/></TD>';
						print '<TD><b>Intérieur</b></TD>';
						print '<TD><input type="text" name="comm_interieur" size="35" value="' . $expertise->comm_interieur . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Plancher</b></TD>';
						print '<TD><input type="text" name="comm_plancher" size="35" value="' . $expertise->comm_plancher . '"/></TD>';
						print '<TD><b>Plancher - Fosse</b></TD>';
						print '<TD><input type="text" name="comm_plancher_fosse" size="35" value="' . $expertise->comm_plancher_fosse . '"/></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>ridelles</b></TD>';
						print '<TD><input type="text" name="comm_ridelles" size="35" value="' . $expertise->comm_ridelles . '"/></TD>';
						print '<TD><input type="text" name="div_porteur_semi" size="20" value="' . $expertise->div_porteur_semi . '"/></TD>';
						print '<TD><input type="text" name="comm_div_porteur_semi" size="35" value="' . $expertise->comm_div_porteur_semi . '"/></TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre">';
						print '<TD colspan="5" align="center">Autres observations</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="5" align="center">';
						$doleditor = new DolEditor('autres_observations', $expertise->autres_observations, '', 80, 'dolibarr_details', 'In', false, false, $conf->global->FCKEDITOR_ENABLE || $conf->global->FCKEDITOR_ENABLE_SOCIETE, 4, 90);
						$doleditor->Create();
						print '</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD colspan="2">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD colspan="2"><b> Expertise faite à </b><input type="text" name="lieu" size="20" value="' . $expertise->lieu . '"/> le ' . $form->select_date($expertise->date_exp, 'date_exp_',0,0,1,'',1,1,1,0,'','','') . '</TD>';
						print '<TD colspan="2"><b> Essai éffectué par ' . $form->select_dolusers($expertise->fk_testeur,'fk_testeur',1) . ' le ' . $form->select_date($expertise->date_essai, 'date_essai_',0,0,1,'',1,1,1,0,'','','') . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="2"><b> L' ."'" . 'utilisateur vendeur' . $form->selectcontacts($reprise->fk_soc,$expertise->fk_client_contact,'fk_client_contact',1) .'</TD>';
						print '<TD colspan="2"><b> Le rédacteur' . $form->select_dolusers($expertise->fk_expert,'fk_expert',1) .'</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="2">Signature et Cachet</TD>';
						print '<TD colspan="2">Signature</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="4"></BR></BR></BR></BR><b>NB : Sous réserve de constatations effectuées par nos ateliers lors de la restitution.</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
	print '</TABLE>';

	print '<div class="tabsAction">';
 	print '<input type="submit" class="button" value="' . $langs->trans("Save") . '">';
	print '&nbsp;<input type="button" class="button" value="' . $langs->trans("Cancel") . '" onClick="javascript:history.go(-1)">';
	print '</div>';
	print '</form>';

} elseif($user->rights->volvo->lireeprise) {
	$formconfirm = '';
	if ($action == 'suppr' && $user->admin) {
		$formconfirm = $form->formconfirm($_SERVER["PHP_SELF"] . '?id=' . $object->id . '&repid=' . $repid . '&exp=' . $exp, 'Supprimer', 'Supprimer la Reprise ?', 'confirm_delete', '', 0, 1);
	}
	print $formconfirm;
	print '<TABLE width="100%">';
		print '<TR>';
			print '<TD valign="top" width="100%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR><img src="' . dol_buildpath('/volvo/img/logo theobald.png',2) . '" height="60" width="142"></TD><TD><H1>ETAT GENERAL DE LA REPRISE</H1></TD></TR>';
				print '</TABLE>';
				print '</br>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD>';
				print '<TABLE width="100%"  class="border">';
					print '<TR class="liste_titre">';
						print '<TD rowspan="4" width="2%" align="center">O</BR>r</BR>g</BR>a</BR>n</BR>e</BR>s</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Moteur</b></TD>';
						print '<TD>' . $expertise->moteur . '</TD>';
						print '<TD><b>Transmission</b></TD>';
						print '<TD>' . $expertise->transmission . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Embrayage</b></TD>';
						print '<TD>' . $expertise->embrayage . '</TD>';
						print '<TD><b>Pont</b></TD>';
						print '<TD>' . $expertise->pont . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Boite de Vitesse</b></TD>';
						print '<TD>' . $expertise->bv . '</TD>';
						print '<TD><b>Freins</b></TD>';
						print '<TD>' . $expertise->freins . '</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="8" width="2%" align="center">E</BR>x</BR>t</BR>é</BR>r</BR>i</BR>e</BR>u</BR>r</BR> </BR>c</BR>a</BR>b</BR>i</BR>n</BR>e</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Déflecteurs G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_defG] . ' / ' . $expertise->liste[1][$expertise->fk_defD] . '</TD>';
						print '<TD><b>Pare choc AV G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_parechoc_av_G] . ' / ' . $expertise->liste[1][$expertise->fk_parechoc_av_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Déflecteur de Toit</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_defT] . '</TD>';
						print '<TD><b>Calandre</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_calandre] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Visière</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_visiere] . '</TD>';
						print '<TD><b>Clignotants AV G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_clignotant_av_G] . ' / ' . $expertise->liste[1][$expertise->fk_clignotant_av_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Rétroviseur accostage</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_retroA] . '</TD>';
						print '<TD><b>Longe de porte G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_longe_porte_G] . ' / ' . $expertise->liste[1][$expertise->fk_longe_porte_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Rétroviseurs G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_retroG] . ' / ' . $expertise->liste[1][$expertise->fk_retroD] . '</TD>';
						print '<TD><b>Portillons de coffre AV G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_porte_coffre_G] . ' / ' . $expertise->liste[1][$expertise->fk_porte_coffre_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Blocs Optiques AV G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_bloc_opt_av_G] . ' / ' . $expertise->liste[1][$expertise->fk_bloc_opt_av_D] . '</TD>';
						print '<TD><b>Portières G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_porte_cabine_G] . ' / ' . $expertise->liste[1][$expertise->fk_porte_cabine_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Enjoliveurs de Phares G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_enjo_phare_av_G] . ' / ' . $expertise->liste[1][$expertise->fk_enjo_phare_av_D] . '</TD>';
						print '<TD>' . $expertise->div_ext_cabine . '</TD>';
						print '<TD>' . $expertise->comm_div_ext_cabine . '</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="9" width="2%" align="center">C</BR>h</BR>â</BR>s</BR>s</BR>i</BR>s</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Roue de secours</b></TD>';
						print '<TD>' . $expertise->liste[3][$expertise->fk_roue_secours] . '</TD>';
						print '<TD><b>Ailes AR G / D</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_aile_ar_G] . ' / ' . $expertise->liste[2][$expertise->fk_aile_ar_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Flexibles électriques / Air</b></TD>';
						print '<TD>' . $expertise->liste[4][$expertise->fk_flexibles] . '</TD>';
						print '<TD><b>Feux AR G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_feux_ar_G] . ' / ' . $expertise->liste[1][$expertise->fk_feux_ar_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Grille alu sur châssis</b></TD>';
						print '<TD>' . $expertise->liste[5][$expertise->fk_grille_alu] . '</TD>';
						print '<TD><b>Supports de feux AR G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_support_feux_ar_G] . ' / ' . $expertise->liste[1][$expertise->fk_support_feux_ar_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Batteries</b></TD>';
						print '<TD>' . $expertise->liste[6][$expertise->fk_batteries] . '</TD>';
						print '<TD><b>Pneu AV % usure</b></TD>';
						print '<TD>' . $expertise->liste[15][$expertise->usure_pneu_av] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Jupes latérales G / D</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_jupe_G] . ' / ' . $expertise->liste[2][$expertise->fk_jupe_D] . '</TD>';
						print '<TD><b>Pneu AR1 % usure</b></TD>';
						print '<TD>' . $expertise->liste[15][$expertise->usure_pneu_ar1] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoirs Gasoil G / D</b></TD>';
						print '<TD>' . $expertise->liste[7][$expertise->fk_reservoir_GO_G] . ' / ' . $expertise->liste[7][$expertise->fk_reservoir_GO_D] . '</TD>';
						print '<TD><b>Pneu AR2 % usure</b></TD>';
						print '<TD>' . $expertise->liste[3][$expertise->usure_pneu_ar2] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoir AdBlue</b></TD>';
						print '<TD>' . $expertise->liste[6][$expertise->fk_reservoir_adblue] . '</TD>';
						print '<TD><b>Pneu AR3 % usure</b></TD>';
						print '<TD>' . $expertise->liste[3][$expertise->usure_pneu_ar3] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoir Hydraulique</b></TD>';
						print '<TD>' . $expertise->liste[8][$expertise->fk_reservoir_hydro] . '</TD>';
						print '<TD>' . $expertise->div_chassis . '</TD>';
						print '<TD>' . $expertise->comm_div_chassis . '</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" >';
						print '<TD rowspan="6" width="2%" align="center">I</BR>n</BR>t</BR>.</BR> </BR>c</BR>a</BR>b</BR>i</BR>n</BR>e</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Kit Outillage + Cric</b></TD>';
						print '<TD>' . $expertise->liste[9][$expertise->fk_kit_outils_cric] . '</TD>';
						print '<TD><b>Autoradio / Téléphone</b></TD>';
						print '<TD>' . $expertise->liste[13][$expertise->fk_autoradio] . ' / ' . $expertise->liste[13][$expertise->fk_telephone] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Chappe de remorquage</b></TD>';
						print '<TD>' . $expertise->liste[10][$expertise->fk_chappe] . '</TD>';
						print '<TD><b>Tapis de Sol / Nombre</b></TD>';
						print '<TD>' . $expertise->liste[13][$expertise->fk_tapis_sol] . ' / ' . $expertise->nb_tapis_sol . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat Interieur</b></TD>';
						print '<TD>' . $expertise->liste[11][$expertise->fk_etat_interieur] . '</TD>';
						print '<TD><b>Pare Brise</b></TD>';
						print '<TD>' . $expertise->liste[14][$expertise->fk_parebrise] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat tableau de bord</b></TD>';
						print '<TD>' . $expertise->liste[12][$expertise->fk_etat_TDB] . '</TD>';
						print '<TD><b>Clé de contact et réservoir</b></TD>';
						print '<TD>' . $expertise->liste[10][$expertise->fk_cles] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat des couchettes</b></TD>';
						print '<TD>' . $expertise->liste[11][$expertise->fk_etat_couchette] . '</TD>';
						print '<TD><b>Kilomètres</b></TD>';
						print '<TD>' . Price($expertise->kilometres) . ' Km</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre">';
						print '<TD rowspan="8" width="2%" align="center">P</BR>o</BR>r</BR>t</BR>e</BR>u</BR>r</BR> </BR>/</BR> </BR>S</BR>e</BR>m</BR>i</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
						print '<TD width="19%" align="center"></TD>';
						print '<TD width="30%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Barre anti-encastrement</b></TD>';
						print '<TD>' . $expertise->comm_barres_AE . '</TD>';
						print '<TD><b>Grue</b></TD>';
						print '<TD>' . $expertise->comm_grue . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Baches</b></TD>';
						print '<TD>' . $expertise->comm_baches . '</TD>';
						print '<TD><b>Hayon</b></TD>';
						print '<TD>' . $expertise->comm_hayon . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Caisse</b></TD>';
						print '<TD>' . $expertise->comm_caisse . '</TD>';
						print '<TD><b>Crochet Attelage</b></TD>';
						print '<TD>' . $expertise->comm_crochet_attelage . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Benne</b></TD>';
						print '<TD>' . $expertise->comm_benne . '</TD>';
						print '<TD><b>Groupe frigo</b></TD>';
						print '<TD>' . $expertise->comm_groupe_frigo . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Portes arrières</b></TD>';
						print '<TD>' . $expertise->comm_portes_ar . '</TD>';
						print '<TD><b>Intérieur</b></TD>';
						print '<TD>' . $expertise->comm_interieur . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Plancher</b></TD>';
						print '<TD>' . $expertise->comm_plancher . '</TD>';
						print '<TD><b>Plancher - Fosse</b></TD>';
						print '<TD>' . $expertise->comm_plancher_fosse . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>ridelles</b></TD>';
						print '<TD>' . $expertise->comm_ridelles . '</TD>';
						print '<TD>' . $expertise->div_porteur_semi . '</TD>';
						print '<TD>' . $expertise->comm_div_porteur_semi . '</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre">';
						print '<TD colspan="5" align="center">Autres observations</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="5" align="center">' .	$expertise->autres_observations . '</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD colspan="2">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD colspan="2"><b> Expertise faite à: </b>' . $expertise->lieu . ' le: ' . dol_print_date($expertise->date_exp, 'daytext') . '</TD>';
						$userstatic = new User($db);
						$result = $userstatic->fetch($expertise->fk_testeur);
						print '<TD colspan="2"><b> Essai éffectué par: </b>' . $userstatic->getFullName($langs) . ' <b>le: </b>' . dol_print_date($expertise->date_essai, 'daytext') . '</TD>';
					print '</TR>';
					print '<TR>';
						$contact = new Contact($db);
						$contact->fetch($expertise->fk_client_contact);
						print '<TD colspan="2"><b> L' ."'" . 'utilisateur vendeur: </b>' . $contact->firstname . ' ' . $contact->lastname . '</TD>';
						$userstatic = new User($db);
						$result = $userstatic->fetch($expertise->fk_expert);
						print '<TD colspan="2"><b> Le rédacteur: </b>' . $userstatic->getFullName($langs) .'</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="2">Signature et Cachet</TD>';
						print '<TD colspan="2">Signature</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="4"></BR></BR></BR></BR><b>NB : Sous réserve de constatations effectuées par nos ateliers lors de la restitution.</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
	print '</TABLE>';

	print '<div class="tabsAction">';
	print '<script>';
	print 'function pop() {';
	print "window.open('".dol_buildpath('/volvo/reprise/expprint.php', 2)."?repid=" . $repid . "&exp=" . $exp . "','height=600,width=600,resible=no');";
	print "}";
	print '</script>';
	if ($user->rights->volvo->modif_exp) {
	print '<div class="inline-block divButAction"><a class="butAction" href="' . $_SERVER['PHP_SELF'] . '?id=' . $id . '&exp=' . $exp . '&action=edit">' . 'Modifier' . "</a></div>\n";
	}
	if ($user->admin) {
		print '<div class="inline-block divButAction"><a class="butAction" href="' . $_SERVER['PHP_SELF'] . '?id=' . $id . '&exp=' . $exp . '&action=suppr">' . 'Supprimer' . "</a></div>\n";
	}
	print '<div class="inline-block divButAction"><a class="butAction" href="#" onClick="pop()">Imprimer</a></div>';
	print '</div>';

}

llxFooter();
$db->close();