<?php
$res = @include '../../main.inc.php'; // For root directory
if (! $res)
	$res = @include '../../../main.inc.php'; // For "custom" directory
if (! $res)
	die("Include of main fails");

dol_include_once('/volvo/class/expertise.class.php');
require_once DOL_DOCUMENT_ROOT . '/contact/class/contact.class.php';
require_once DOL_DOCUMENT_ROOT . '/user/class/user.class.php';

$exp = GETPOST('exp', 'int');

$expertise = new Expertise($db);
$expertise->fetch($exp);

print '<HTML>';
print '<HEAD>';
print '<link rel="stylesheet" type="text/css" href="'.dol_buildpath('/volvo/reprise/style_print.css.php',2).'?lang=fr_FR&amp;theme=eldy&amp;optioncss=print&amp;userid=1&amp;entity=1&amp;version=3.9.0">';
print '</HEAD>';
print '<DIV width="20cm" style="font-size:10px">';

print '<TABLE width="100%">';
		print '<TR>';
			print '<TD valign="top" width="100%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR><TD width="30%" rowspan="2"><img src="' . dol_buildpath('/volvo/img/logo theobald.png',2) . '" height="60" width="142"></TD><TD><H2>ETAT GENERAL DE LA REPRISE</H2></TD></TR>';
				print '</TABLE>';
				print '</br>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD>';
				print '<TABLE width="100%"  class="border">';
					print '<TR class="liste_titre">';
						print '<TD rowspan="4" width="2%" align="center">O</BR>r</BR>g</BR>a</BR>n</BR>e</BR>s</TD>';
						print '<TD width="22%" align="center"></TD>';
						print '<TD width="27%" align="center">Expertise</TD>';
						print '<TD width="22%" align="center"></TD>';
						print '<TD width="27%" align="center">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Moteur</b></TD>';
						print '<TD>' . $expertise->moteur . '</TD>';
						print '<TD><b>Transmission</b></TD>';
						print '<TD>' . $expertise->transmission . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Embrayage</b></TD>';
						print '<TD>' . $expertise->embrayage . '</TD>';
						print '<TD><b>Pont</b></TD>';
						print '<TD>' . $expertise->pont . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Boite de Vitesse</b></TD>';
						print '<TD>' . $expertise->bv . '</TD>';
						print '<TD><b>Freins</b></TD>';
						print '<TD>' . $expertise->freins . '</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" style="height:0px;">';
						print '<TD rowspan="8" align="center">E</BR>x</BR>t</BR>é</BR>r</BR>i</BR>e</BR>u</BR>r</BR> </BR>c</BR>a</BR>b</BR>i</BR>n</BR>e</TD>';
						print '<TD align="center" style="display:none;"></TD>';
						print '<TD align="center" style="display:none;">Expertise</TD>';
						print '<TD align="center" style="display:none;"></TD>';
						print '<TD align="center" style="display:none;">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Déflecteurs G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_defG] . ' / ' . $expertise->liste[1][$expertise->fk_defD] . '</TD>';
						print '<TD><b>Pare choc AV G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_parechoc_av_G] . ' / ' . $expertise->liste[1][$expertise->fk_parechoc_av_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Déflecteur de Toit</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_defT] . '</TD>';
						print '<TD><b>Calandre</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_calandre] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Visière</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_visiere] . '</TD>';
						print '<TD><b>Clignotants AV G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_clignotant_av_G] . ' / ' . $expertise->liste[1][$expertise->fk_clignotant_av_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Rétroviseur accostage</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_retroA] . '</TD>';
						print '<TD><b>Longe de porte G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_longe_porte_G] . ' / ' . $expertise->liste[1][$expertise->fk_longe_porte_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Rétroviseurs G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_retroG] . ' / ' . $expertise->liste[1][$expertise->fk_retroD] . '</TD>';
						print '<TD><b>Portillons de coffre AV G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_porte_coffre_G] . ' / ' . $expertise->liste[1][$expertise->fk_porte_coffre_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Blocs Optiques AV G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_bloc_opt_av_G] . ' / ' . $expertise->liste[1][$expertise->fk_bloc_opt_av_D] . '</TD>';
						print '<TD><b>Portières G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_porte_cabine_G] . ' / ' . $expertise->liste[1][$expertise->fk_porte_cabine_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Enjoliveurs de Phares G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_enjo_phare_av_G] . ' / ' . $expertise->liste[1][$expertise->fk_enjo_phare_av_D] . '</TD>';
						print '<TD>' . $expertise->div_ext_cabine . '</TD>';
						print '<TD>' . $expertise->comm_div_ext_cabine . '</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" style="height:0px;">';
						print '<TD rowspan="9" align="center">C</BR>h</BR>â</BR>s</BR>s</BR>i</BR>s</TD>';
						print '<TD align="center" style="display:none;"></TD>';
						print '<TD align="center" style="display:none;">Expertise</TD>';
						print '<TD align="center" style="display:none;"></TD>';
						print '<TD align="center" style="display:none;">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Roue de secours</b></TD>';
						print '<TD>' . $expertise->liste[3][$expertise->fk_roue_secours] . '</TD>';
						print '<TD><b>Ailes AR G / D</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_aile_ar_G] . ' / ' . $expertise->liste[2][$expertise->fk_aile_ar_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Flexibles électriques / Air</b></TD>';
						print '<TD>' . $expertise->liste[4][$expertise->fk_flexibles] . '</TD>';
						print '<TD><b>Feux AR G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_feux_ar_G] . ' / ' . $expertise->liste[1][$expertise->fk_feux_ar_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Grille alu sur châssis</b></TD>';
						print '<TD>' . $expertise->liste[5][$expertise->fk_grille_alu] . '</TD>';
						print '<TD><b>Supports de feux AR G / D</b></TD>';
						print '<TD>' . $expertise->liste[1][$expertise->fk_support_feux_ar_G] . ' / ' . $expertise->liste[1][$expertise->fk_support_feux_ar_D] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Batteries</b></TD>';
						print '<TD>' . $expertise->liste[6][$expertise->fk_batteries] . '</TD>';
						print '<TD><b>Pneu AV % usure</b></TD>';
						print '<TD>' . $expertise->liste[15][$expertise->usure_pneu_av] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Jupes latérales G / D</b></TD>';
						print '<TD>' . $expertise->liste[2][$expertise->fk_jupe_G] . ' / ' . $expertise->liste[2][$expertise->fk_jupe_D] . '</TD>';
						print '<TD><b>Pneu AR1 % usure</b></TD>';
						print '<TD>' . $expertise->liste[15][$expertise->usure_pneu_ar1] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoirs Gasoil G / D</b></TD>';
						print '<TD>' . $expertise->liste[7][$expertise->fk_reservoir_GO_G] . ' / ' . $expertise->liste[7][$expertise->fk_reservoir_GO_D] . '</TD>';
						print '<TD><b>Pneu AR2 % usure</b></TD>';
						print '<TD>' . $expertise->liste[3][$expertise->usure_pneu_ar2] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoir AdBlue</b></TD>';
						print '<TD>' . $expertise->liste[6][$expertise->fk_reservoir_adblue] . '</TD>';
						print '<TD><b>Pneu AR3 % usure</b></TD>';
						print '<TD>' . $expertise->liste[3][$expertise->usure_pneu_ar3] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Réservoir Hydraulique</b></TD>';
						print '<TD>' . $expertise->liste[8][$expertise->fk_reservoir_hydro] . '</TD>';
						print '<TD>' . $expertise->div_chassis . '</TD>';
						print '<TD>' . $expertise->comm_div_chassis . '</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" style="height:0px;">';
						print '<TD rowspan="6" align="center">I</BR>n</BR>t</BR>.</BR> </BR>c</BR>a</BR>b</BR>i</BR>n</BR>e</TD>';
						print '<TD align="center" style="display:none;"></TD>';
						print '<TD align="center" style="display:none;">Expertise</TD>';
						print '<TD align="center" style="display:none;"></TD>';
						print '<TD align="center" style="display:none;">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Kit Outillage + Cric</b></TD>';
						print '<TD>' . $expertise->liste[9][$expertise->fk_kit_outils_cric] . '</TD>';
						print '<TD><b>Autoradio / Téléphone</b></TD>';
						print '<TD>' . $expertise->liste[13][$expertise->fk_autoradio] . ' / ' . $expertise->liste[13][$expertise->fk_telephone] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Chappe de remorquage</b></TD>';
						print '<TD>' . $expertise->liste[10][$expertise->fk_chappe] . '</TD>';
						print '<TD><b>Tapis de Sol / Nombre</b></TD>';
						print '<TD>' . $expertise->liste[13][$expertise->fk_tapis_sol] . ' / ' . $expertise->nb_tapis_sol . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat Interieur</b></TD>';
						print '<TD>' . $expertise->liste[11][$expertise->fk_etat_interieur] . '</TD>';
						print '<TD><b>Pare Brise</b></TD>';
						print '<TD>' . $expertise->liste[14][$expertise->fk_parebrise] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat tableau de bord</b></TD>';
						print '<TD>' . $expertise->liste[12][$expertise->fk_etat_TDB] . '</TD>';
						print '<TD><b>Clé de contact et réservoir</b></TD>';
						print '<TD>' . $expertise->liste[10][$expertise->fk_cles] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Etat des couchettes</b></TD>';
						print '<TD>' . $expertise->liste[11][$expertise->fk_etat_couchette] . '</TD>';
						print '<TD><b>Kilomètres</b></TD>';
						print '<TD>' . Price($expertise->kilometres) . ' Km</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre" style="height:0px;">';
						print '<TD rowspan="8" align="center">P</BR>o</BR>r</BR>t</BR>e</BR>u</BR>r</BR> </BR>/</BR> </BR>S</BR>e</BR>m</BR>i</TD>';
						print '<TD align="center" style="display:none;"></TD>';
						print '<TD align="center" style="display:none;">Expertise</TD>';
						print '<TD align="center" style="display:none;"></TD>';
						print '<TD align="center" style="display:none;">Expertise</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Barre anti-encastrement</b></TD>';
						print '<TD>' . $expertise->comm_barres_AE . '</TD>';
						print '<TD><b>Grue</b></TD>';
						print '<TD>' . $expertise->comm_grue . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Baches</b></TD>';
						print '<TD>' . $expertise->comm_baches . '</TD>';
						print '<TD><b>Hayon</b></TD>';
						print '<TD>' . $expertise->comm_hayon . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Caisse</b></TD>';
						print '<TD>' . $expertise->comm_caisse . '</TD>';
						print '<TD><b>Crochet Attelage</b></TD>';
						print '<TD>' . $expertise->comm_crochet_attelage . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Benne</b></TD>';
						print '<TD>' . $expertise->comm_benne . '</TD>';
						print '<TD><b>Groupe frigo</b></TD>';
						print '<TD>' . $expertise->comm_groupe_frigo . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Portes arrières</b></TD>';
						print '<TD>' . $expertise->comm_portes_ar . '</TD>';
						print '<TD><b>Intérieur</b></TD>';
						print '<TD>' . $expertise->comm_interieur . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>Plancher</b></TD>';
						print '<TD>' . $expertise->comm_plancher . '</TD>';
						print '<TD><b>Plancher - Fosse</b></TD>';
						print '<TD>' . $expertise->comm_plancher_fosse . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD><b>ridelles</b></TD>';
						print '<TD>' . $expertise->comm_ridelles . '</TD>';
						print '<TD>' . $expertise->div_porteur_semi . '</TD>';
						print '<TD>' . $expertise->comm_div_porteur_semi . '</TD>';
					print '</TR>';
					print '<TR>';
					print '</TR>';
					print '<TR class="liste_titre">';
						print '<TD colspan="5" align="center">Autres observations</TD>';
					print '</TR>';
					print '<TR style="page-break-before:always">';
						print '<TD colspan="5" align="center">' .	$expertise->autres_observations . '</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD colspan="2">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD colspan="2"><b> Expertise faite à: </b>' . $expertise->lieu . ' le: ' . dol_print_date($expertise->date_exp, 'daytext') . '</TD>';
						$userstatic = new User($db);
						$result = $userstatic->fetch($expertise->fk_testeur);
						print '<TD colspan="2"><b> Essai éffectué par: </b>' . $userstatic->getFullName($langs) . ' <b>le: </b>' . dol_print_date($expertise->date_essai, 'daytext') . '</TD>';
					print '</TR>';
					print '<TR>';
						$contact = new Contact($db);
						$contact->fetch($expertise->fk_client_contact);
						print '<TD colspan="2"><b> L' ."'" . 'utilisateur vendeur: </b>' . $contact->firstname . ' ' . $contact->lastname . '</TD>';
						$userstatic = new User($db);
						$result = $userstatic->fetch($expertise->fk_expert);
						print '<TD colspan="2"><b> Le rédacteur: </b>' . $userstatic->getFullName($langs) .'</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="2">Signature et Cachet</TD>';
						print '<TD colspan="2">Signature</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD colspan="4"></BR></BR></BR></BR><b>NB : Sous réserve de constatations effectuées par nos ateliers lors de la restitution.</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
	print '</TABLE>';

print '</DIV>';
print '</HTML>';