<?php
$res = @include '../../main.inc.php'; // For root directory
if (! $res)
	$res = @include '../../../main.inc.php'; // For "custom" directory
if (! $res)
	die("Include of main fails");

require_once DOL_DOCUMENT_ROOT . '/volvo/class/reprise.class.php';

$repid = GETPOST('repid', 'int');

$reprise = new Reprise($db);
if (isset($repid)){
	$reprise->fetch($repid);
 	$reprise->fetch_thirdparty();
}

$img0 = img_picto('non','statut0');
$img1 = img_picto('non','statut6');

	print '<HTML>';
	print '<HEAD>';
	print '<link rel="stylesheet" type="text/css" href="' . dol_buildpath('/volvo/reprise/style_print.css.php',2) . '?lang=fr_FR&amp;theme=eldy&amp;optioncss=print&amp;userid=1&amp;entity=1&amp;&pagef=l&amp;version=3.9.0">';
	print '</HEAD>';
	print '<DIV width="27.5cm" style="font-size:10px">';
	print '<TABLE width="100%"  class="border">';
		print '<TR>';
			print '<TD colspan="2" valign="top" width="100%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR><TD width="30%" rowspan="2"><img src="' . dol_buildpath('/volvo/img/logo theobald.png',2) . '" height="60" width="142"></TD><TD colspan="2"><H1>FICHE SIGNALETIQUE VEHICULE DE REPRISE</H1></TD></TR>';
					print '<TR><TD width="35%">Référence : ' . $reprise->ref . '</TD><TD width="35%">Police : ' . $reprise->police . '</TD></TR>';
				print '</TABLE>';
				print '</br>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD colspan="2" width="100%" valign="top">';
				print '<TABLE width="100%" class="nobordernopadding">';
					print '<TR>';
						print '<TD class="fieldrequired" width="25%">Proprietaire</TD>';
						print '<TD class="fieldrequired" width="10%" rowspan="2">Adresse</TD>';
						print '<TD class="valeur" width="35%" rowspan="2">' . dol_format_address($reprise->thirdparty,0,"</br>") . '</TD>';
						print '<TD class="fieldrequired" width="15%">' . "Date d'entree prévue" . '</TD>';
						print '<TD class="valeur" width="15%">' . dol_print_date($reprise->date_entree, 'daytext') . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="valeur">' . $reprise->thirdparty->name . '</TD>';
						print '<TD class="fieldrequired">' . "Site de restitution" . '</TD>';
						print '<TD class="valeur">' . $reprise->sites[$reprise->fk_restit] . '</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD width="50%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD class="Valeur" width="50%" colspan="2"><b>Marque : </b>' . $reprise->marque[$reprise->fk_marque] . '</TD>';
						print '<TD class="Valeur" width="50%" colspan="2"><b>Genre : </b>' . $reprise->genre[$reprise->fk_genre] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>Type : </b>' . $reprise->type . '</TD>';
						print '<TD class="Valeur" colspan="2"><b>Silouhette : </b>' . $reprise->silouhette[$reprise->fk_silouhette] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>N° de série : </b>' . $reprise->numserie . '</TD>';
						print '<TD class="Valeur" colspan="2"><b>Norme : </b>' . $reprise->norme[$reprise->fk_norme] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" width="25%"><b>Carrosserie</b></TD>';
						print '<TD class="Valeur" colspan="3" width="75%">' . $reprise->carrosserie . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>Puissance Commerciale : </b>' . $reprise->puiscom . ' Cv</TD>';
						print '<TD class="Valeur" colspan="2"><b>Puissance Fiscale : </b>' . $reprise->puisfisc . ' Cv</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>PTC : </b>' . $reprise->ptc . ' Tonnes</TD>';
						print '<TD class="Valeur" colspan="2"><b>PV : </b>' . $reprise->pv . ' Tonnes</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>PTR : </b>' . $reprise->ptr . ' Tonnes</TD>';
						print '<TD class="Valeur" colspan="2"><b>Charge Utile : </b>' . $reprise->chargutil . ' Tonnes</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>Longueur Utile : </b>' . $reprise->longutil . ' m</TD>';
						print '<TD class="Valeur" colspan="2"><b>Largeur Utile : </b>' . $reprise->largutil . ' m</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>Places assises : </b>' . $reprise->place . '</TD>';
						print '<TD class="Valeur" colspan="2"></TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
			print '<TD width="50%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD class="Valeur" width="46%" colspan="2"><b>immatriculation : </b>' . $reprise->immat . '</TD>';
						print '<TD class="Valeur" width="54%" colspan="2"><b>1ere mise en circ. : </b>' . dol_print_date($reprise->circ, 'daytext') . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>Kilometrage actuel : </b>' . $reprise->kmact . ' km</TD>';
						print '<TD class="Valeur" colspan="2"><b>Km prévu a la restitution : </b>' . $reprise->kmrestit . ' km</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="4"></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="4"></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" width="73%" colspan="3"><b>Validité des mines : (> 3 mois à l’entrée véhicule)  : </b></TD>';
						print '<TD class="Valeur" width="27%">' . dol_print_date($reprise->validmine, 'daytext') . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="3"><b>Validité du Tachygraphe (> 3 mois à l’entrée véhicule): </b></TD>';
						print '<TD class="Valeur">' . dol_print_date($reprise->validtachy, 'daytext') . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="3"><b>Validité ' . $reprise->valid1 . ': (> 3 mois)</b></TD>';
						print '<TD class="Valeur">' . dol_print_date($reprise->date1, 'daytext') . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="3"><b>Validité ' . $reprise->valid2 . ': (> 3 mois)</b></TD>';
						print '<TD class="Valeur">' . dol_print_date($reprise->date2, 'daytext') . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="3"><b>Certificat Agrément ' . $reprise->agrement . ': (> 3 mois)</b></TD>';
						print '<TD class="Valeur">' . dol_print_date($reprise->dateagrement, 'daytext') . '</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD width="50%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD class="Valeur" width="45%" colspan="2"><b>Cabine : </b>' . $reprise->cabine[$reprise->fk_cabine] . '</TD>';
						print '<TD class="Valeur" width="55%" colspan="2"><b>Suspension de cabine : </b>' . $reprise->suspcabine[$reprise->fk_suspcabine] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur"colspan="2"><b>Moteur : </b>' . $reprise->moteur[$reprise->fk_moteur] . '</TD>';
						print '<TD class="Valeur" colspan="2"><b>Ralentisseur : </b>' . $reprise->ralentisseur[$reprise->fk_ralentisseur] . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>Boite de vitesses : </b>' . $reprise->bv[$reprise->fk_bv] . '</TD>';
						print '<TD class="Valeur" colspan="2"><b>Rapport : </b>' . $reprise->rav . ' + ' . $reprise->rar . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>pont : </b>' . $reprise->show_picto($reprise->sr) . '<b> SR</b>&emsp;' . $reprise->show_picto($reprise->dr) . '<b> DR</b>&emsp;' . $reprise->show_picto($reprise->blocage) . '<b> Blocage</b></TD>';
						print '<TD class="Valeur" colspan="2"><b>Rapport de pont : </b>' . $reprise->rapport . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="2"><b>Freinage : </b>' . $reprise->freinage[$reprise->fk_freinage] . '</TD>';
						print '<TD class="Valeur" colspan="2">' . $reprise->show_picto($reprise->abs1) . '<b> ABS</b>&emsp;' . $reprise->show_picto($reprise->asr) .  '<b> ASR</b>&emsp;' .  $reprise->show_picto($reprise->ebs) . '<b> EBS</b>&emsp;' . $reprise->show_picto($reprise->esp) . '<b> ESP</b>&emsp;' . $reprise->show_picto($reprise->dfr) . '<b> DFR</b></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" rowspan="2"><b>Suspension Chassis : </b></TD>';
						print '<TD class="Valeur" width="11%"><b>Avant : </b></TD>';
						print '<TD class="Valeur" colspan="2">' . $reprise->suspav . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur"><b>Arrière : </b></TD>';
						print '<TD class="Valeur" colspan="2">' . $reprise->suspar . '</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
			print '<TD width="50%" align="center" valign="top">';
			print "<b>Informations sur l'état et la qualité des pneumatiques</b></br>";
				print '<TABLE width="98%" style="border-collapse:collapse">';
					print '<TR>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="12%" align="center">Emp.</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="20%" align="center">Marque</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="36%" align="center" colspan="3">Taille</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="20%" align="center">Profil</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="12%" align="center" colspan="2">Usure</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="12%" align="center">AV</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="20%" align="center">' . $reprise->marquepneu[$reprise->fk_mav] . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="24%" align="center">' . $reprise->tav . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="4%" align="center">R</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="8%" align="center">' . $reprise->dav . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="20%" align="center">' . $reprise->pav . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="8%" align="center">' . $reprise->uav . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="4%" align="center">%</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="12%" align="center">AR1</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="20%" align="center">' . $reprise->marquepneu[$reprise->fk_mar1] . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="24%" align="center">' . $reprise->tar1 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="4%" align="center">R</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="8%" align="center">' . $reprise->dar1 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="20%" align="center">' . $reprise->par1 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="8%" align="center">' . $reprise->uar1 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="4%" align="center">%</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="12%" align="center">AR2</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="20%" align="center">' . $reprise->marquepneu[$reprise->fk_mar2] . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="24%" align="center">' . $reprise->tar2 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="4%" align="center">R</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="8%" align="center">' . $reprise->dar2 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="20%" align="center">' . $reprise->par2 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="8%" align="center">' . $reprise->uar2 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="4%" align="center">%</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="12%" align="center">AR3</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="20%" align="center">' . $reprise->marquepneu[$reprise->fk_mar3] . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="24%" align="center">' . $reprise->tar3 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="4%" align="center">R</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="8%" align="center">' . $reprise->dar3 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="20%" align="center">' . $reprise->par3 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="valeur" width="8%" align="center">' . $reprise->uar3 . '</TD>';
						print '<TD style="border-style:solid; border-color:black; border-width:1px" class="fieldrequired" width="4%" align="center">%</TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD colspan="2" valign="top" width="100%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD class="Valeur" width="25%" colspan="2"><b>Chassis : </b>' . $reprise->show_picto($reprise->nisoude) . '<b> Ni soudé</b>&emsp;&emsp;' . $reprise->show_picto($reprise->nifissure) . '<b> Ni fissuré</b></TD>';
						print '<TD class="Valeur" width="25%" colspan="2"><b>Nb réservoir GO : </b>' . $reprise->nbreserv . '</TD>';
						print '<TD class="Valeur" width="25%" colspan="2"><b>Capacité Gasoil : </b>' . $reprise->capago . ' litres</TD>';
						print '<TD class="Valeur" width="25%" colspan="2"><b>Capacité AdBlue : </b>' . $reprise->adblue . ' litres</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" colspan="4"><b>Etat mécanique : </b>' . $reprise->etatmeca . '</TD>';
						print '<TD class="Valeur" colspan="4"><b>Présentation : </b>' . $reprise->pres . '</TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->lve) . '<b> 2 LVE</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->rct) . '<b> 2 RCT</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->gyro) . '<b> Gyrophare</b></TD>';
						print '<TD class="Valeur" width="25%" colspan="2">' . $reprise->show_picto($reprise->echapv) . '<b> Echappement vertical</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->adr) . '<b> adr</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->hydro) . '<b> Hydrolique</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->Compresseur) . '<b> Compresseur</b></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" width="25%" Colspan="2">' . $reprise->show_picto($reprise->climtoit) . '<b> Climatisation de toit</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->clim) . '<b> Climatisation</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->webasto) . '<b> Webasto</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->deflecteur) . '<b> Déflecteurs</b></TD>';
						print '<TD class="Valeur" width="12.5%">' . $reprise->show_picto($reprise->jupes) . '<b> Jupes</b></TD>';
						print '<TD class="Valeur" width="25%" Colspan="2"></TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
		print '<TR>';
			print '<TD colspan="2" valign="top" width="100%" valign="top">';
				print '<TABLE width="100%"  class="nobordernopadding">';
					print '<TR>';
						print '<TD class="Valeur" width="100%" Colspan="6" align=center><b>Documents a récupérer</b></TD>';
					print '</TR>';
					print '<TR>';
						print '<TD class="Valeur" width="15%"></TD>';
						print '<TD class="Valeur" width="15%">' . $reprise->show_picto($reprise->copiecg) . '<b> Copie Carte Grise</b></TD>';
						print '<TD class="Valeur" width="25%">' . $reprise->show_picto($reprise->copiect) . '<b> Copie dernier controle technique</b></TD>';
						print '<TD class="Valeur" width="20%">' . $reprise->show_picto($reprise->copieca) . '<b> Copie certificat agrément</b></TD>';
						print '<TD class="Valeur" width="10%">' . $reprise->show_picto($reprise->photo) . '<b> Photos</b></TD>';
						print '<TD class="Valeur" width="15%"></TD>';
					print '</TR>';
				print '</TABLE>';
			print '</TD>';
		print '</TR>';
	print '</TABLE>';
	print '</BR>';
	print '</BR>';

print '</DIV>';
print '</HTML>';