CREATE TABLE llx_immat (
  rowid int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  genre integer,
  marque integer,
  type_veh varchar(200),
  energie varchar(200),
  carrosserie integer,
  const_dist varchar(200),
  ptr integer,
  gvw varchar(200),
  charutpl integer,
  puissfisc integer,
  fk_soc integer,
  status varchar(1),
  csp_prop varchar(200),
  dt_carte_grise date,
  immat varchar(200),
  vin varchar(200),
  num_serie varchar(200),
  modele varchar(200),
  volume varchar(200),
  county varchar(200),
  fk_user integer,
  fk_lead integer,
  fk_order integer,
  import_key varchar(100),
  tms timestamp
) ENGINE=InnoDB DEFAULT CHARSET=utf8;